### ISSUE TITLE
BUG: If saving target folder contains an emoji web clipper does not save

### ISSUE THREAD

**Issue by merqrial** [obsidianmd/obsidian-clipper#109]
**Version (please complete the following information):**
 - OS: Windows
 - Browser Brave
 - Web Clipper version: 0.9.4
- Obsidian version: 1.7.4

**Describe the bug**
Brilliant extension. Thank you for this.

When I opened the default template and chose a different folder name, it did not save.
I tried playing around with the folders in my vault and it could save correctly when the folder names did not contain emojis. 
The folder name (an existing folder in my vault) is, `2-areas\🎈 leisure\articles`
I tried with just `2-areas` it was able to save under the folder just fine.

**To reproduce**
1. Go to any article
2. Click on Obsidian web clipper
3. Update folder to any folder which has a emoji
4. No error but article does not save.

**Expected behavior**
Article is saved in the correct folder even when the folder path contains emoji

**Your template file**
Just the default template, no change except the folder change.

**Comment by NWiddup** [comment]
@merqrial FWIW I was able to get this to work using forward slash (/) instead of backslash (\) in the path.

Clipper:
![image](https://github.com/user-attachments/assets/8eaa06fb-255e-4026-b0cd-185e99734aeb)
Saved into Obsidian:
![image](https://github.com/user-attachments/assets/29a4a36e-a2f4-47e1-b700-d6b3aebf79f5)

I get an error in the dev console if i use backslash. Obsidian comes to the foreground, but doesn't add the clipping.
Console (showing the previous working snip, as well as the failed snip):
![image](https://github.com/user-attachments/assets/f6743e72-1825-490f-bc39-4bd9bb20bc07)

**Comment by kepano** [comment]
Good catch. In the future will add some error detection in the path settings to check for `\`
