### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by ezekini** [obsidianmd/obsidian-clipper#203]
**Version (please complete the following information):**

- OS: Mac os 15.1.1 (24B91)
- Browser: Arc (chromium based)
- Web Clipper version: 0.9.8
- Obsidian version: 1.7.7

**Describe the bug**

I created a template with behaviour "Add to an existing note, at the top". When I save a webpage, it is added to a folder named "Links interesantes" and each subsequent web I clip creates a new note inside that folder. Am I missing something? 

Also note that the warning "Adding to an existing note or daily note requires Obsidian 1.7.2 or later" is confusing. is it informing me that I must have those versiones and I don't or just informing? 

**Expected behavior**

My understanding is that all clipped pages should go to the same note when this behaviour is selected. I just want to save the titlte and URL, like a bookmark manager.

**Your template file**
![image](https://github.com/user-attachments/assets/c43d6d1c-46a6-4570-881b-9fd9edc962ae)

**Comment by Evantix** [comment]
@ezekini The properties will likely be overwritten because they are being added to the same page, which can only hold one set of properties. 


I was trying to do similar stuff but, every time I add a link, it appears with extra spaces, preventing me from adding it to the table automatically. 

![image](https://github.com/user-attachments/assets/4e417af0-1024-4f4f-8af8-65eac8006488)
![image](https://github.com/user-attachments/assets/00b16bdf-e972-4733-941a-752f69e19410)



And this should look like this. 
![image](https://github.com/user-attachments/assets/92d43ea3-0fe2-457a-9dc6-679b2c0ad09b)

**Comment by kepano** [comment]
This is working as expected. I think you are confusing note title and note location. It sounds like you want `Links interesantes` as the note title not the path.

Please use the support channels for help with templates.

**Comment by Evantix** [comment]
@kepano I'm not really concerned about the formatting of the links; my main issue is the automatic spaces added when incorporating this into the same note, for example, at the bottom. 
![image](https://github.com/user-attachments/assets/f37aad2a-3a9a-470f-9664-b3e596e457cb)

I have the spaces between the links added automatically
![image](https://github.com/user-attachments/assets/57127d1a-c448-4b99-a478-0cb3f97eeec4)


and I need to manually remove them to make the table work
![image](https://github.com/user-attachments/assets/3c3925b2-7ce2-4890-95a6-17cbaf9776bf)

I’m not sure if I’m overthinking this, but I would prefer to save HTTPS links in a single table within one file, rather than having to clip the entire page and rely on the Dataview plugin. 

Many thanks for help.

**Comment by kepano** [comment]
Obsidian URI always adds a newline when appending/prepending, it's unrelated to Web Clipper. You will need to open a feature request on the Obsidian forum if you want to have more control over that.

**Comment by Evantix** [comment]
Thank you! I understand why it didn't work. I'll submit future requests, and for now, I'll manually delete the spaces.
