### ISSUE TITLE
Errors about invalid file path from Omnisearch

### ISSUE THREAD

**Issue by luckman212** [obsidianmd/obsidian-clipper#46]
Wish I had taken a screenshot and now I can't repro, but...

I tested this plugin v0.4.8 + Chrome 129.0.6668.59 on macOS against the following page:

```
https://news.ycombinator.com/item?id=41567262
```

I saw 2 errors in my Obsidian console from Omnisearch complaining about "invalid file path". I assume due to the pipe char `|` being part of the filename(?)

The chars `\ / : * ? " < > |` should be automatically converted to something cross-platform filesystem friendly like a plain hyphen `-` or a space.

**Comment by kepano** [comment]
Pipe is a legal character for file names on macOS. Obsidian allows files to be created based on the current OS restrictions. I assume Omnisearch is complaining because it's not Windows-compatible file name. However you can use the `safe_name` filter if you want more aggressive multiplatform filtering.

**Comment by brpaz** [comment]
I got a similar error on Fedora Linux, when clipping some websites with special chars on the title.

```
Filename cannot contain any of the following characters \/:
```

Will try your suggestion of using `safe_name`

**Comment by kepano** [comment]
More restrictive file names will be added for Linux in the next version

**Comment by luckman212** [comment]
Thanks @kepano I didn't know about `{{title|safe_name}}`.
